In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

In [2]:
df1 = pd.read_csv('../excel_files/train.csv')
df2 = pd.read_csv('../excel_files/test.csv')

df = pd.concat([df1, df2], ignore_index=True)

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [3]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [4]:
columns_to_fill = ['LotFrontage', 'GarageYrBlt', 'GarageArea', 'BsmtUnfSF', 'TotalBsmtSF'] 

median_values = df[columns_to_fill].median()

df[columns_to_fill] = df[columns_to_fill].fillna(median_values)

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [5]:
missing_values = df[columns_to_fill].isnull().sum()

missing_values = missing_values[missing_values == 0]

missing_values

LotFrontage    0
GarageYrBlt    0
GarageArea     0
BsmtUnfSF      0
TotalBsmtSF    0
dtype: int64

In [6]:
columns_to_fill = ['MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath'] 

df[columns_to_fill] = df[columns_to_fill].fillna(0)

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [7]:
missing_values = df[columns_to_fill].isnull().sum()

missing_values = missing_values[missing_values == 0]

missing_values

MasVnrArea      0
BsmtFinSF1      0
BsmtFinSF2      0
BsmtFullBath    0
BsmtHalfBath    0
dtype: int64

In [8]:
df['GarageYrBlt'] = df['GarageYrBlt'].replace(2207, df['GarageYrBlt'].median())
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [9]:
df['GarageCars'] = df['GarageCars'].fillna(2)

df['GarageCars'].isnull().sum()

0

In [10]:
df = df.drop(columns=['YearBuilt'])

df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

In [11]:
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

len(numerical_columns), numerical_columns

(37,
 Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
        'OverallCond', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
        'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
        'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
        'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
        'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
        'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
        'MoSold', 'YrSold', 'SalePrice'],
       dtype='object'))

In [12]:
missing_values = df[numerical_columns].isnull().sum()

missing_values = missing_values[missing_values > 0]

missing_values

SalePrice    1459
dtype: int64

In [13]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [14]:
object_columns = df.select_dtypes(include=['object']).columns

len(object_columns), object_columns

(43,
 Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
        'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
        'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
        'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
        'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
        'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
        'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
        'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
        'SaleType', 'SaleCondition'],
       dtype='object'))

In [15]:
missing_values = df[object_columns].isnull().sum()

missing_values = missing_values[missing_values > 0]

missing_values.index.to_list()

['MSZoning',
 'Alley',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType']

In [16]:
missing_values

MSZoning           4
Alley           2721
Utilities          2
Exterior1st        1
Exterior2nd        1
MasVnrType      1766
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinType2      80
Electrical         1
KitchenQual        1
Functional         2
FireplaceQu     1420
GarageType       157
GarageFinish     159
GarageQual       159
GarageCond       159
PoolQC          2909
Fence           2348
MiscFeature     2814
SaleType           1
dtype: int64

In [17]:
object_columns_with_missing_values = ['MSZoning',
 'Alley',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType']

df[object_columns_with_missing_values] = df[object_columns_with_missing_values].fillna('NotPresent')

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NotPresent,IR1,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NotPresent,IR1,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NotPresent,IR1,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,6,2006,WD,Normal,NaN
2915,2916,160,RM,21.0,1894,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,4,2006,WD,Abnorml,NaN
2916,2917,20,RL,160.0,20000,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,9,2006,WD,Abnorml,NaN
2917,2918,85,RL,62.0,10441,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,2919,60,RL,74.0,9627,Pave,NotPresent,Reg,Lvl,AllPub,...,0,NotPresent,NotPresent,NotPresent,0,11,2006,WD,Normal,NaN

In [18]:
missing_counts = df.isnull().sum()

columns_with_missing_values = missing_counts[missing_counts > 0].index.tolist()

columns_with_missing_values

['SalePrice']

In [19]:
df['AgeCalculated'] = df['YrSold'] - df['YearRemodAdd']

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,AgeCalculated
0,1,60,RL,65.0,8450,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,2,2008,WD,Normal,208500.0,5
1,2,20,RL,80.0,9600,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,5,2007,WD,Normal,181500.0,31
2,3,60,RL,68.0,11250,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,9,2008,WD,Normal,223500.0,6
3,4,70,RL,60.0,9550,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,2,2006,WD,Abnorml,140000.0,36
4,5,60,RL,84.0,14260,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,12,2008,WD,Normal,250000.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,21.0,1936,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,6,2006,WD,Normal,NaN,36
2915,2916,160,RM,21.0,1894,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,4,2006,WD,Abnorml,NaN,36
2916,2917,20,RL,160.0,20000,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,9,2006,WD,Abnorml,NaN,10
2917,2918,85,RL,62.0,10441,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,MnPrv,Shed,700,7,2006,WD,Normal,NaN,14
2918,2919,60,RL,74.0,9627,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0,11,2006,WD,Normal,NaN,12

In [20]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice',
       'AgeCalculated'],
      dtype='object')

In [21]:
columns_to_scale = ['LotFrontage', 'LotArea', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 
                    'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'GarageArea',
                    'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 
                    'PoolArea', 'MiscVal', 'YearRemodAdd', 'YrSold', 'GarageYrBlt', 'AgeCalculated']

scaler = MinMaxScaler()

df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,AgeCalculated
0,1,60,RL,0.150685,0.033420,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,2,0.50,WD,Normal,208500.0,0.112903
1,2,20,RL,0.202055,0.038795,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,5,0.25,WD,Normal,181500.0,0.532258
2,3,60,RL,0.160959,0.046507,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,9,0.50,WD,Normal,223500.0,0.129032
3,4,70,RL,0.133562,0.038561,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,2,0.00,WD,Abnorml,140000.0,0.612903
4,5,60,RL,0.215753,0.060576,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,12,0.50,WD,Normal,250000.0,0.161290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,0.000000,0.002973,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,6,0.00,WD,Normal,NaN,0.612903
2915,2916,160,RM,0.000000,0.002776,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,4,0.00,WD,Abnorml,NaN,0.612903
2916,2917,20,RL,0.476027,0.087406,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,9,0.00,WD,Abnorml,NaN,0.193548
2917,2918,85,RL,0.140411,0.042726,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,MnPrv,Shed,0.041176,7,0.00,WD,Normal,NaN,0.258065
2918,2919,60,RL,0.181507,0.038921,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,11,0.00,WD,Normal,NaN,0.225806

In [22]:
df.to_csv('../excel_files/data_check_1.csv', index=False)

In [23]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,AgeCalculated
0,1,60,RL,0.150685,0.033420,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,2,0.50,WD,Normal,208500.0,0.112903
1,2,20,RL,0.202055,0.038795,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,5,0.25,WD,Normal,181500.0,0.532258
2,3,60,RL,0.160959,0.046507,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,9,0.50,WD,Normal,223500.0,0.129032
3,4,70,RL,0.133562,0.038561,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,2,0.00,WD,Abnorml,140000.0,0.612903
4,5,60,RL,0.215753,0.060576,Pave,NotPresent,IR1,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,12,0.50,WD,Normal,250000.0,0.161290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2915,160,RM,0.000000,0.002973,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,6,0.00,WD,Normal,NaN,0.612903
2915,2916,160,RM,0.000000,0.002776,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,4,0.00,WD,Abnorml,NaN,0.612903
2916,2917,20,RL,0.476027,0.087406,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,9,0.00,WD,Abnorml,NaN,0.193548
2917,2918,85,RL,0.140411,0.042726,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,MnPrv,Shed,0.041176,7,0.00,WD,Normal,NaN,0.258065
2918,2919,60,RL,0.181507,0.038921,Pave,NotPresent,Reg,Lvl,AllPub,...,NotPresent,NotPresent,NotPresent,0.000000,11,0.00,WD,Normal,NaN,0.225806

In [24]:
categorical_columns = ['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
                        'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
                        'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
                        'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
                        'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
                        'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
                        'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
                        'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
                        'SaleType', 'SaleCondition', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 
                        'HalfBath', 'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'MoSold',
                        'MSSubClass', 'OverallQual', 'OverallCond', 'BedroomAbvGr', 'KitchenAbvGr']

one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_columns)], remainder="passthrough")

transformed_df = transformer.fit_transform(df)

transformed_df

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 208570 stored elements and shape (2919, 398)>

In [25]:
dense_array_df = transformed_df.toarray()

dense_array_df

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e-01, 2.08500000e+05, 1.12903226e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.50000000e-01, 1.81500000e+05, 5.32258065e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e-01, 2.23500000e+05, 1.29032258e-01],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00,            nan, 1.93548387e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00,            nan, 2.58064516e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00,            nan, 2.25806452e-01]])

In [26]:
df_sparsed = pd.DataFrame(dense_array_df)

df_sparsed

,0,1,2,3,4,5,6,7,8,9,...,388,389,390,391,392,393,394,395,396,397
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.082210,0.000000,0.0,0.0,0.0,0.000000,0.50,208500.0,0.112903
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.209270,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.25,181500.0,0.532258
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.056604,0.000000,0.0,0.0,0.0,0.000000,0.50,223500.0,0.129032
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.047170,0.268775,0.0,0.0,0.0,0.000000,0.00,140000.0,0.612903
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.134831,0.113208,0.000000,0.0,0.0,0.0,0.000000,0.50,250000.0,0.161290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00,NaN,0.612903
2915,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.032345,0.000000,0.0,0.0,0.0,0.000000,0.00,NaN,0.612903
2916,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.332865,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.00,NaN,0.193548
2917,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.056180,0.043127,0.000000,0.0,0.0,0.0,0.041176,0.00,NaN,0.258065
2918,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.133427,0.064690,0.000000,0.0,0.0,0.0,0.000000,0.00,NaN,0.225806

In [27]:
df_sparsed_train = df_sparsed.iloc[:1460]
df_sparsed_test = df_sparsed.iloc[1460:]

df_sparsed_train[373]

0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
         ...
1455    1456.0
1456    1457.0
1457    1458.0
1458    1459.0
1459    1460.0
Name: 373, Length: 1460, dtype: float64

In [28]:
df_sparsed_train.to_csv('../excel_files/df_sparsed_train.csv', index=False)
df_sparsed_test.to_csv('../excel_files/df_sparsed_test.csv', index=False)