In [1]:
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from torch import nn
from pathlib import Path
import numpy as np
from torchmetrics.regression import MeanAbsolutePercentageError
device = "mps" if torch.backends.mps.is_available() else "cpu"

In [61]:
df = pd.read_csv('../excel_files/df_sparsed_train.csv')

df

,0,1,2,3,4,5,6,7,8,9,...,388,389,390,391,392,393,394,395,396,397
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.082210,0.000000,0.0,0.0,0.0,0.000000,0.50,208500.0,0.112903
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.209270,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.25,181500.0,0.532258
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.056604,0.000000,0.0,0.0,0.0,0.000000,0.50,223500.0,0.129032
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.047170,0.268775,0.0,0.0,0.0,0.000000,0.00,140000.0,0.612903
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.134831,0.113208,0.000000,0.0,0.0,0.0,0.000000,0.50,250000.0,0.161290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.053908,0.000000,0.0,0.0,0.0,0.000000,0.25,175000.0,0.145161
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.245084,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.00,210000.0,0.387097
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.080863,0.000000,0.0,0.0,0.0,0.147059,1.00,266500.0,0.096774
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.257022,0.000000,0.110672,0.0,0.0,0.0,0.000000,1.00,142125.0,0.258065
1459,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.516854,0.091644,0.000000,0.0,0.0,0.0,0.000000,0.50,147500.0,0.725806

In [62]:
X = df.drop(columns=["373", "396"])

y = df["396"]

In [63]:
X

,0,1,2,3,4,5,6,7,8,9,...,387,388,389,390,391,392,393,394,395,397
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.368280,0.000000,0.082210,0.000000,0.0,0.0,0.0,0.000000,0.50,0.112903
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.309140,0.209270,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.25,0.532258
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.408602,0.000000,0.056604,0.000000,0.0,0.0,0.0,0.000000,0.50,0.129032
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.431452,0.000000,0.047170,0.268775,0.0,0.0,0.0,0.000000,0.00,0.612903
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.561828,0.134831,0.113208,0.000000,0.0,0.0,0.0,0.000000,0.50,0.161290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.309140,0.000000,0.053908,0.000000,0.0,0.0,0.0,0.000000,0.25,0.145161
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.336022,0.245084,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.00,0.387097
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.169355,0.000000,0.080863,0.000000,0.0,0.0,0.0,0.147059,1.00,0.096774
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.161290,0.257022,0.000000,0.110672,0.0,0.0,0.0,0.000000,1.00,0.258065
1459,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.185484,0.516854,0.091644,0.000000,0.0,0.0,0.0,0.000000,0.50,0.725806

In [64]:
y

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: 396, Length: 1460, dtype: float64

In [65]:
X_tensor = torch.tensor(X.values, dtype=torch.float).to(device)
y_tensor = torch.tensor(y.values, dtype=torch.float).to(device)

X_tensor.shape, y_tensor.shape, len(X_tensor), len(y_tensor), X_tensor.device, y_tensor.device

(torch.Size([1460, 396]),
 torch.Size([1460]),
 1460,
 1460,
 device(type='mps', index=0),
 device(type='mps', index=0))

In [66]:
RANDOM_SEED = 42
X_train, X_test, y_train, y_test = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=RANDOM_SEED)

X_train.shape, y_train.shape, X_test.shape, y_test.shape, len(X_train), X_train.device

(torch.Size([1168, 396]),
 torch.Size([1168]),
 torch.Size([292, 396]),
 torch.Size([292]),
 1168,
 device(type='mps', index=0))

In [67]:
X_train.shape[1]

396

In [68]:
class HousePricingModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_stack = nn.Sequential(
            nn.Linear(in_features=X_train.shape[1], out_features=512),
            nn.ReLU(),
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(in_features=512, out_features=16),
            nn.ReLU(),
            nn.ReLU(),
            nn.Linear(in_features=16, out_features=1),
        )
    def forward(self, x):
        return self.layer_stack(x)

In [69]:
torch.manual_seed(RANDOM_SEED)
model_0 = HousePricingModelV0()
model_0.to(device)
model_0

HousePricingModelV0(
  (layer_stack): Sequential(
    (0): Linear(in_features=396, out_features=512, bias=True)
    (1): ReLU()
    (2): ReLU()
    (3): Dropout(p=0.3, inplace=False)
    (4): Linear(in_features=512, out_features=16, bias=True)
    (5): ReLU()
    (6): ReLU()
    (7): Linear(in_features=16, out_features=1, bias=True)
  )
)

In [70]:
y_pred_temp = model_0(X_train)

y_pred_temp

tensor([[0.0008],
        [0.0310],
        [0.0172],
        ...,
        [0.0305],
        [0.0227],
        [0.0297]], device='mps:0', grad_fn=<LinearBackward0>)

In [71]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.Adam(params=model_0.parameters(), lr=0.001)
mean_abs_percentage_error = MeanAbsolutePercentageError().to(device)

In [72]:
torch.manual_seed(RANDOM_SEED)
epochs = 50000
for epoch in range(epochs):
    model_0.train()
    y_pred = model_0(X_train).squeeze()
    loss = loss_fn(y_pred, y_train)
    mape = mean_abs_percentage_error(y_pred, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

    model_0.eval()
    with torch.inference_mode():
        test_pred = model_0(X_test).squeeze()
        test_loss = loss_fn(test_pred, y_test)
        test_mape = mean_abs_percentage_error(test_pred, y_test)
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch: {epoch+1}/{epochs} | {loss = :.2f} | {mape = :.2f} | {test_loss = :.2f} | {test_mape = :.2f}")

Epoch: 1000/50000 | loss = 41824.92 | mape = 0.23 | test_loss = 45612.61 | test_mape = 0.26
Epoch: 2000/50000 | loss = 25756.90 | mape = 0.13 | test_loss = 28602.44 | test_mape = 0.15
Epoch: 3000/50000 | loss = 20078.06 | mape = 0.11 | test_loss = 22951.63 | test_mape = 0.13
Epoch: 4000/50000 | loss = 16398.13 | mape = 0.09 | test_loss = 20428.20 | test_mape = 0.12
Epoch: 5000/50000 | loss = 15410.71 | mape = 0.08 | test_loss = 19322.06 | test_mape = 0.11
Epoch: 6000/50000 | loss = 14828.75 | mape = 0.08 | test_loss = 18844.15 | test_mape = 0.11
Epoch: 7000/50000 | loss = 14242.71 | mape = 0.08 | test_loss = 18450.85 | test_mape = 0.11
Epoch: 8000/50000 | loss = 14351.30 | mape = 0.08 | test_loss = 18224.90 | test_mape = 0.11
Epoch: 9000/50000 | loss = 13743.32 | mape = 0.08 | test_loss = 18047.90 | test_mape = 0.11
Epoch: 10000/50000 | loss = 13971.89 | mape = 0.08 | test_loss = 17870.65 | test_mape = 0.10
Epoch: 11000/50000 | loss = 13491.66 | mape = 0.08 | test_loss = 17746.33 | test_mape = 0.10
Epoch: 12000/50000 | loss = 13414.98 | mape = 0.08 | test_loss = 17594.63 | test_mape = 0.10
Epoch: 13000/50000 | loss = 12996.39 | mape = 0.07 | test_loss = 17483.30 | test_mape = 0.10
Epoch: 14000/50000 | loss = 12953.42 | mape = 0.07 | test_loss = 17269.80 | test_mape = 0.10
Epoch: 15000/50000 | loss = 12755.18 | mape = 0.07 | test_loss = 17106.57 | test_mape = 0.10
Epoch: 16000/50000 | loss = 12903.53 | mape = 0.07 | test_loss = 17050.96 | test_mape = 0.10
Epoch: 17000/50000 | loss = 12858.77 | mape = 0.07 | test_loss = 17013.00 | test_mape = 0.10
Epoch: 18000/50000 | loss = 12647.15 | mape = 0.07 | test_loss = 16910.78 | test_mape = 0.10
Epoch: 19000/50000 | loss = 12643.91 | mape = 0.07 | test_loss = 16813.93 | test_mape = 0.10
Epoch: 20000/50000 | loss = 12766.43 | mape = 0.07 | test_loss = 16771.99 | test_mape = 0.10
Epoch: 21000/50000 | loss = 12477.85 | mape = 0.07 | test_loss = 16685.92 | test_mape = 0.10
Epoch: 22000/50000 | loss = 12849.73 | mape = 0.07 | test_loss = 16613.96 | test_mape = 0.10
Epoch: 23000/50000 | loss = 12353.86 | mape = 0.07 | test_loss = 16505.24 | test_mape = 0.10
Epoch: 24000/50000 | loss = 12410.63 | mape = 0.07 | test_loss = 16438.60 | test_mape = 0.10
Epoch: 25000/50000 | loss = 12160.15 | mape = 0.07 | test_loss = 16338.01 | test_mape = 0.10
Epoch: 26000/50000 | loss = 12350.68 | mape = 0.07 | test_loss = 16330.78 | test_mape = 0.10
Epoch: 27000/50000 | loss = 12001.93 | mape = 0.07 | test_loss = 16241.57 | test_mape = 0.09
Epoch: 28000/50000 | loss = 12087.46 | mape = 0.07 | test_loss = 16177.04 | test_mape = 0.09
Epoch: 29000/50000 | loss = 12230.95 | mape = 0.07 | test_loss = 16153.68 | test_mape = 0.09
Epoch: 30000/50000 | loss = 12360.31 | mape = 0.07 | test_loss = 16100.56 | test_mape = 0.09
Epoch: 31000/50000 | loss = 12189.94 | mape = 0.07 | test_loss = 16079.34 | test_mape = 0.09
Epoch: 32000/50000 | loss = 12040.25 | mape = 0.07 | test_loss = 15992.00 | test_mape = 0.09
Epoch: 33000/50000 | loss = 12320.20 | mape = 0.07 | test_loss = 16050.28 | test_mape = 0.09
Epoch: 34000/50000 | loss = 11838.86 | mape = 0.07 | test_loss = 15979.75 | test_mape = 0.09
Epoch: 35000/50000 | loss = 11543.00 | mape = 0.07 | test_loss = 15941.03 | test_mape = 0.09
Epoch: 36000/50000 | loss = 11972.03 | mape = 0.07 | test_loss = 15929.98 | test_mape = 0.09
Epoch: 37000/50000 | loss = 11995.89 | mape = 0.07 | test_loss = 15848.46 | test_mape = 0.09
Epoch: 38000/50000 | loss = 11796.88 | mape = 0.07 | test_loss = 15884.68 | test_mape = 0.09
Epoch: 39000/50000 | loss = 11927.89 | mape = 0.07 | test_loss = 15858.61 | test_mape = 0.09
Epoch: 40000/50000 | loss = 11413.96 | mape = 0.06 | test_loss = 15787.67 | test_mape = 0.09
Epoch: 41000/50000 | loss = 11891.65 | mape = 0.07 | test_loss = 15749.35 | test_mape = 0.09
Epoch: 42000/50000 | loss = 11477.55 | mape = 0.07 | test_loss = 15801.46 | test_mape = 0.09
Epoch: 43000/50000 | loss = 11289.62 | mape = 0.06 | test_loss = 15777.62 | test_mape = 0.09
Epoch: 44000/50000 | loss = 11736.65 | mape = 0.07 | test_loss = 15809.56 | test_mape = 0.09
Epoch: 45000/50000 | loss = 11352.63 | mape = 0.06 | test_loss = 15892.38 | test_mape = 0.09
Epoch: 46000/50000 | loss = 11740.52 | mape = 0.07 | test_loss = 15892.24 | test_mape = 0.09
Epoch: 47000/50000 | loss = 11242.82 | mape = 0.06 | test_loss = 15883.31 | test_mape = 0.09
Epoch: 48000/50000 | loss = 11635.64 | mape = 0.07 | test_loss = 15939.67 | test_mape = 0.09
Epoch: 49000/50000 | loss = 11121.28 | mape = 0.06 | test_loss = 15988.15 | test_mape = 0.09
Epoch: 50000/50000 | loss = 11308.54 | mape = 0.06 | test_loss = 15959.02 | test_mape = 0.09

Stucked at 16749...

In [77]:
MODEL_NAME = "house_prices_prediction_model_0.pth"
MODEL_PATH = Path("../models")
MODEL_PATH.mkdir(parents=True, exist_ok=True)
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME
torch.save(obj=model_0.state_dict(), f=MODEL_SAVE_PATH)

In [84]:
df_test = pd.read_csv('../excel_files/df_sparsed_test.csv')

df_test

,0,1,2,3,4,5,6,7,8,9,...,388,389,390,391,392,393,394,395,396,397
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.098315,0.000000,0.0,0.0,0.208333,0.0,0.000000,1.0,NaN,0.822581
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.275983,0.048518,0.0,0.0,0.000000,0.0,0.735294,1.0,NaN,0.870968
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.148876,0.045822,0.0,0.0,0.000000,0.0,0.000000,1.0,NaN,0.225806
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.252809,0.048518,0.0,0.0,0.000000,0.0,0.000000,1.0,NaN,0.225806
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.110512,0.0,0.0,0.250000,0.0,0.000000,1.0,NaN,0.322581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,NaN,0.612903
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.032345,0.0,0.0,0.000000,0.0,0.000000,0.0,NaN,0.612903
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.332865,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,NaN,0.193548
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.056180,0.043127,0.0,0.0,0.000000,0.0,0.041176,0.0,NaN,0.258065
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.133427,0.064690,0.0,0.0,0.000000,0.0,0.000000,0.0,NaN,0.225806

In [85]:
df_test_temp = df_test.drop(columns=["373", "396"])

df_test_temp

,0,1,2,3,4,5,6,7,8,9,...,387,388,389,390,391,392,393,394,395,397
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.490591,0.098315,0.000000,0.0,0.0,0.208333,0.0,0.000000,1.0,0.822581
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.209677,0.275983,0.048518,0.0,0.0,0.000000,0.0,0.735294,1.0,0.870968
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.323925,0.148876,0.045822,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.315860,0.252809,0.048518,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.340054,0.000000,0.110512,0.0,0.0,0.250000,0.0,0.000000,1.0,0.322581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.192204,0.000000,0.032345,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.387097,0.332865,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.193548
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.056180,0.043127,0.0,0.0,0.000000,0.0,0.041176,0.0,0.258065
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.436828,0.133427,0.064690,0.0,0.0,0.000000,0.0,0.000000,0.0,0.225806

In [86]:
X_test_tensor = torch.tensor(df_test_temp.values, dtype=torch.float).to(device)

X_tensor.shape

torch.Size([1460, 396])

In [87]:
torch.manual_seed(RANDOM_SEED)
model_0.eval()
with torch.inference_mode():
    y_result_preds = model_0(X_test_tensor)
y_result_preds

tensor([[118626.7969],
        [173092.3438],
        [190760.7969],
        ...,
        [167588.7656],
        [124499.7656],
        [220188.6094]], device='mps:0')

In [88]:
y_result_preds_np = y_result_preds.cpu().numpy()
y_result_preds_np

array([[118626.8  ],
       [173092.34 ],
       [190760.8  ],
       ...,
       [167588.77 ],
       [124499.766],
       [220188.61 ]], dtype=float32)

In [90]:
df_test_temp['Id'] = df_test['373']

df_test_temp

,0,1,2,3,4,5,6,7,8,9,...,388,389,390,391,392,393,394,395,397,Id
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.098315,0.000000,0.0,0.0,0.208333,0.0,0.000000,1.0,0.822581,1461.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.275983,0.048518,0.0,0.0,0.000000,0.0,0.735294,1.0,0.870968,1462.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.148876,0.045822,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806,1463.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.252809,0.048518,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806,1464.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.110512,0.0,0.0,0.250000,0.0,0.000000,1.0,0.322581,1465.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903,2915.0
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.032345,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903,2916.0
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.332865,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.193548,2917.0
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.056180,0.043127,0.0,0.0,0.000000,0.0,0.041176,0.0,0.258065,2918.0
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.133427,0.064690,0.0,0.0,0.000000,0.0,0.000000,0.0,0.225806,2919.0

In [92]:
y_result_preds_np = y_result_preds_np.astype(int)
y_result_preds_np

array([[118626],
       [173092],
       [190760],
       ...,
       [167588],
       [124499],
       [220188]])

In [93]:
df_test_temp['SalePrice'] = y_result_preds_np

df_test_temp

,0,1,2,3,4,5,6,7,8,9,...,389,390,391,392,393,394,395,397,Id,SalePrice
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.0,0.0,0.208333,0.0,0.000000,1.0,0.822581,1461.0,118626
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.048518,0.0,0.0,0.000000,0.0,0.735294,1.0,0.870968,1462.0,173092
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.045822,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806,1463.0,190760
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.048518,0.0,0.0,0.000000,0.0,0.000000,1.0,0.225806,1464.0,192049
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.110512,0.0,0.0,0.250000,0.0,0.000000,1.0,0.322581,1465.0,198998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903,2915.0,71436
1455,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,...,0.032345,0.0,0.0,0.000000,0.0,0.000000,0.0,0.612903,2916.0,82977
1456,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.193548,2917.0,167588
1457,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.043127,0.0,0.0,0.000000,0.0,0.041176,0.0,0.258065,2918.0,124499
1458,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.064690,0.0,0.0,0.000000,0.0,0.000000,0.0,0.225806,2919.0,220188

In [97]:
df_result = df_test_temp[['Id', 'SalePrice']]

df_result['Id'] = df_result['Id'].astype(int)

df_result

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_5371/1076689619.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result['Id'] = df_result['Id'].astype(int)

        Id  SalePrice
0     1461     118626
1     1462     173092
2     1463     190760
3     1464     192049
4     1465     198998
...    ...        ...
1454  2915      71436
1455  2916      82977
1456  2917     167588
1457  2918     124499
1458  2919     220188

[1459 rows x 2 columns]

In [98]:
df_result.to_csv('../excel_files/upload.csv', index=False)